name: assignment_gosi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  glass: ^2.0.0+1
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  flutter_bloc: ^8.1.6
  get_it: ^8.0.0









dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: EuclidSquare
      fonts:
        - asset: assets/fonts/EuclidSquare-Regular.ttf
        - asset: assets/fonts/EuclidSquare-Bold.ttf

    - family: EuclidSquare-M
      fonts:
        - asset: assets/fonts/EuclidSquare-Medium.ttf
          weight: 700





