// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPSb45LSUYePTO8RNmOznsRs4vpOoX3AU',
    appId: '1:748305348351:web:26dd8ab11b5f31eab73eca',
    messagingSenderId: '748305348351',
    projectId: 'gosi-63899',
    authDomain: 'gosi-63899.firebaseapp.com',
    storageBucket: 'gosi-63899.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhOqrkK3Aky6VsjE0HKWKgFlUlzRZeVnA',
    appId: '1:748305348351:android:7096dea49dcf72aab73eca',
    messagingSenderId: '748305348351',
    projectId: 'gosi-63899',
    storageBucket: 'gosi-63899.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFGw9FXMUGj0YLno_AJEzPBfgtYN1P5vM',
    appId: '1:748305348351:ios:92817447da183435b73eca',
    messagingSenderId: '748305348351',
    projectId: 'gosi-63899',
    storageBucket: 'gosi-63899.appspot.com',
    iosBundleId: 'com.example.assignmentGosi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFGw9FXMUGj0YLno_AJEzPBfgtYN1P5vM',
    appId: '1:748305348351:ios:92817447da183435b73eca',
    messagingSenderId: '748305348351',
    projectId: 'gosi-63899',
    storageBucket: 'gosi-63899.appspot.com',
    iosBundleId: 'com.example.assignmentGosi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPSb45LSUYePTO8RNmOznsRs4vpOoX3AU',
    appId: '1:748305348351:web:ae62b29c0d5780eab73eca',
    messagingSenderId: '748305348351',
    projectId: 'gosi-63899',
    authDomain: 'gosi-63899.firebaseapp.com',
    storageBucket: 'gosi-63899.appspot.com',
  );
}
